version: '2'

services:
  app:
    build:
      context: .
    command: run
    external_links:
      - mailhog
      - db
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - '127.0.0.1:8000:8000'
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
