version: '2'

services:
  app:
    # Force the platform to be linux/amd64: https://stackoverflow.com/questions/62807717/how-can-i-solve-postgresql-scram-authentifcation-problem#comment124700935_70238851
    platform: linux/amd64
    build:
      context: .
    command: run
    external_links:
      - mailhog
      - db
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - '127.0.0.1:8000:8000'
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
