# Generated by Django 3.2 on 2022-06-15 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="parents",
            field=models.ManyToManyField(
                related_name="_auth_demo_user_parents_+", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
