# Generated by Django 3.2 on 2022-06-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_demo", "0004_subscription_thirdpartyapp_thirdpartyappactionpermission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thirdpartyappactionpermission",
            old_name="url",
            new_name="url_name",
        ),
    ]
